name: Schema Migrator test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/schema-migrator.yaml"
      - "components/schema-migrator/**"
      - "scripts/**"

permissions:
  id-token: write # This is required for requesting the JWT token
  contents: read # This is required for actions/checkout

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: components/schema-migrator/go.mod
    - name: Run tests
      run: make -C components/schema-migrator release
